name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ['3.10', '3.11']
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e src/google-adk/
      - name: Run tests
        run: pytest
      - name: Run linter
        run: |
          pip install pylint
          pylint --rcfile=src/google-adk/pylintrc src/
      - name: Build Docker image
        run: docker build -t vibe-coding-agentic-apps:latest .